"""The `aqara_lanlink.export_overlay` service.

Renders the local overlay as a Python `TraitSpec`-literal block ready
to paste into a per-model package's `overrides.py` `OVERRIDES` dict.
The user attaches the result to a GitHub issue; the maintainer folds
the entries into the shipped catalogue. This closes the
discovery-to-catalogue feedback loop.

The renderer is a pure function (`render_overlay`) so tests can verify
it without touching HA's persistent-notification infrastructure.
"""
from __future__ import annotations

import logging

from homeassistant.components import persistent_notification as pn
from homeassistant.core import HomeAssistant, ServiceCall

from ..const import DOMAIN
from ..device.overlay import Overlay
from ..device.traits import TraitSpec

_LOGGER = logging.getLogger(__name__)


def render_overlay(overlay: Overlay, *, model: str | None) -> str:
    """Render the overlay (optionally restricted to one model) as a
    pasteable Python snippet.
    """
    if model is not None:
        models = [model] if overlay.has_traits_for_model(model) else []
    else:
        models = sorted(overlay._traits.keys())
    if not models:
        return _no_entries_message(model)
    sections = [_render_model_section(overlay, m) for m in models]
    return "\n\n".join(sections)


def _render_model_section(overlay: Overlay, model: str) -> str:
    traits = overlay.traits_for_model(model)
    provenance = overlay.all_provenance().get(model, {})
    header = (
        f"# {model} - add to the model package's overrides.py OVERRIDES dict.\n"
        f"# Generated by aqara_lanlink.export_overlay; review each entry "
        f"for functionality and usefulness before submitting a PR.\n"
        f"OVERRIDES: dict[str, TraitSpec | None] = {{"
    )
    rows: list[str] = []
    for pid in sorted(traits):
        spec = traits[pid]
        prov = provenance.get(pid)
        prov_comment = ""
        if prov is not None:
            prov_comment = (
                f"    # discovered_from={prov.discovered_from} "
                f"discovered_at={prov.discovered_at.isoformat()}\n"
            )
        rows.append(prov_comment + f"    {_render_trait_row(pid, spec)},")
    return header + "\n" + "\n".join(rows) + "\n}"


def _render_trait_row(pid: str, spec: TraitSpec) -> str:
    """Render one `"pid": TraitSpec(...)` row."""
    kwargs: list[str] = [
        f"id={_quote(spec.id)}",
        f"name={_quote(spec.name)}",
    ]
    if spec.wire_path:
        kwargs.append(f"wire_path={_quote(spec.wire_path)}")
    kwargs.append(f"data_type={_quote(spec.data_type)}")
    if spec.unit:
        kwargs.append(f"unit={_quote(spec.unit)}")
    if spec.platform:
        kwargs.append(f"platform={_quote(spec.platform)}")
    if spec.device_class:
        kwargs.append(f"device_class={_quote(spec.device_class)}")
    if spec.enum_values:
        kwargs.append(f"enum_values={spec.enum_values!r}")
    if spec.auto_clear_seconds is not None:
        kwargs.append(f"auto_clear_seconds={spec.auto_clear_seconds!r}")
    if spec.readable is not True:
        kwargs.append(f"readable={spec.readable!r}")
    if spec.writable is not True:
        kwargs.append(f"writable={spec.writable!r}")
    if spec.trait_id is not None:
        kwargs.append(f"trait_id={spec.trait_id!r}")
    body = ",\n        ".join(kwargs)
    return f"{_quote(pid)}: TraitSpec(\n        {body},\n    )"


def _quote(s: str) -> str:
    """Render `s` as a Python string literal via repr().

    repr() escapes newlines, quotes, backslashes, and other control
    characters, so an untrusted cloud/device-sourced field cannot break out
    of the literal and inject statements into the generated overrides.py. (The
    hand-rolled predecessor escaped only backslash and double-quote, leaving a
    newline injection open.)
    """
    return repr(s)


def _no_entries_message(model: str | None) -> str:
    if model is None:
        return "# Overlay is empty - no overlay entries to export."
    return f"# Overlay has no overlay entries for {model}."


def render_resource_id_map(model: str, resource_id_map: dict[str, str]) -> str:
    """Render the owner-discovered wire_path -> resource_id pairs (Part 1).

    `resource_id_map` is `{wire_path: rid}`, harvested from an OWNED device's
    qlink/trait/read propertyId (authoritative). The maintainer folds these in
    as the `resource_id` on the matching catalogue traits - the reliable
    pairings the build-time joiner could not produce.
    """
    if not resource_id_map:
        return f"# {model} - no wire_path<->rid pairs discovered."
    header = (
        f"# {model} - wire_path -> resource_id pairs discovered from an OWNED "
        f"device's\n"
        f"# qlink/trait/read propertyId (authoritative). The maintainer adds "
        f"these as\n"
        f"# resource_id on the matching catalogue traits. Review before "
        f"submitting a PR.\n"
        f"RESOURCE_IDS: dict[str, str] = {{"
    )
    rows = [
        f"    {_quote(wire_path)}: {_quote(resource_id_map[wire_path])},"
        for wire_path in sorted(resource_id_map)
    ]
    return header + "\n" + "\n".join(rows) + "\n}"


async def async_handle_export(hass: HomeAssistant, call: ServiceCall) -> None:
    """Render the overlay for the integration's first config entry and
    post a Persistent Notification with the result.
    """
    entries = hass.config_entries.async_entries(DOMAIN)
    if not entries:
        _LOGGER.warning(
            "export_overlay called but no Aqara LAN Link entries are loaded"
        )
        return
    entry = entries[0]
    overlay: Overlay = entry.runtime_data.overlay
    model = call.data.get("model")
    rendered = render_overlay(overlay, model=model)
    pn.async_create(
        hass,
        rendered,
        title="Aqara LAN Link overlay export",
        notification_id=f"aqara_lanlink_overlay_export_{entry.entry_id}",
    )
