"""JSON-data + Python-overrides loader for V3 catalogue model packages.

Each per-model package has the layout:
    device/models/<pkg>/
        data.json     # auto-generated by tools/generate_catalogue.py
        __init__.py   # 3-line shim that calls load_model_data
        overrides.py  # hand-edited; OVERRIDES: dict[str, TraitSpec | None]

load_model_data returns the standard public-API contract the registry
indexes and the catalog module consumes.
"""
from __future__ import annotations

import dataclasses
import importlib.util
import json
from pathlib import Path

from custom_components.aqara_lanlink.device.traits import TraitSpec

def load_model_data(pkg_dir: Path) -> dict:
    raw = json.loads((pkg_dir / "data.json").read_text())
    base_traits: dict[str, TraitSpec] = {}
    for wp, fields in raw["traits"].items():
        base_traits[wp] = TraitSpec(id=wp, wire_path=wp, **fields)
    ov_mod = _load_overrides_module(pkg_dir)
    overrides = (getattr(ov_mod, "OVERRIDES", {}) or {}) if ov_mod else {}
    merged_traits = _apply_overrides(base_traits, overrides)
    capabilities = (getattr(ov_mod, "CAPABILITIES", {}) or {}) if ov_mod else {}
    out = {
        "MODELS": tuple(raw["models"]),
        "MANUFACTURER": raw["manufacturer"],
        "DISPLAY_NAME": raw["display_name"],
        "REGIONS": tuple(raw["regions"]),
        "BUNDLE_IDS": tuple(raw["bundle_ids"]),
        "ENDPOINTS": {int(k): v for k, v in raw["endpoints"].items()},
        "DEVICE_TYPES": tuple(raw["device_types"]),
        "CAPABILITIES": dict(capabilities),
        "TRAITS": merged_traits,
    }
    # whitelabels is optional in data.json; only emit WHITELABELS when the
    # package has them, so packages without don't accidentally shadow the
    # registry's getattr(mod, "WHITELABELS", None) fallback with an empty
    # dict that would still pass validation but skip the display-name path.
    if raw.get("whitelabels"):
        out["WHITELABELS"] = dict(raw["whitelabels"])
    # dropped_paths is the set of V3 wire paths the trait_policy excluded
    # from the catalogue. Exposed so observed_path_cache and gap_report
    # treat these as "known but ignored" -- pushed values get silently
    # consumed instead of surfacing as candidate-paths repair issues.
    if raw.get("dropped_paths"):
        out["DROPPED_PATHS"] = tuple(raw["dropped_paths"])
    return out


def _load_overrides_module(pkg_dir: Path):
    overrides_path = pkg_dir / "overrides.py"
    if not overrides_path.exists():
        return None
    spec = importlib.util.spec_from_file_location(
        f"_aqara_overrides_{pkg_dir.name}", overrides_path,
    )
    if spec is None or spec.loader is None:
        return None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _apply_overrides(
    base: dict[str, TraitSpec],
    overrides: dict[str, TraitSpec | None],
) -> dict[str, TraitSpec]:
    merged = dict(base)
    for wp, spec in overrides.items():
        if spec is None:
            merged.pop(wp, None)
        elif spec.wire_path is None:
            # Mirror data.json (which forces wire_path=<key>): a wire_path-less
            # override must still get one from its key, or subscribe+seed and
            # report routing -- both keyed on wire_path -- would silently skip it.
            merged[wp] = dataclasses.replace(spec, wire_path=wp)
        else:
            merged[wp] = spec
    return merged
